-- Records every change of the synced tables in sync_changes (see src/db/schema/device-sync.ts).
-- Rows an incoming sync is writing (sync_applying) are skipped so they are not echoed back;
-- sync_capture_guard pauses everything (account wipe on deletion).
INSERT INTO `sync_capture_guard` (`id`, `paused`) VALUES (1, 0) ON CONFLICT(`id`) DO NOTHING;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_onboarding_state_insert` AFTER INSERT ON `onboarding_state` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'onboarding_state' AND record_id = NEW.user_id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('onboarding_state', NEW.user_id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_onboarding_state_update` AFTER UPDATE ON `onboarding_state` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'onboarding_state' AND record_id = NEW.user_id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('onboarding_state', NEW.user_id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_onboarding_state_delete` AFTER DELETE ON `onboarding_state` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'onboarding_state' AND record_id = OLD.user_id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('onboarding_state', OLD.user_id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_generation_profiles_insert` AFTER INSERT ON `generation_profiles` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'generation_profiles' AND record_id = NEW.user_id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('generation_profiles', NEW.user_id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_generation_profiles_update` AFTER UPDATE ON `generation_profiles` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'generation_profiles' AND record_id = NEW.user_id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('generation_profiles', NEW.user_id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_generation_profiles_delete` AFTER DELETE ON `generation_profiles` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'generation_profiles' AND record_id = OLD.user_id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('generation_profiles', OLD.user_id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_nutrition_settings_insert` AFTER INSERT ON `nutrition_settings` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'nutrition_settings' AND record_id = NEW.athlete_id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('nutrition_settings', NEW.athlete_id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_nutrition_settings_update` AFTER UPDATE ON `nutrition_settings` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'nutrition_settings' AND record_id = NEW.athlete_id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('nutrition_settings', NEW.athlete_id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_nutrition_settings_delete` AFTER DELETE ON `nutrition_settings` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'nutrition_settings' AND record_id = OLD.athlete_id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('nutrition_settings', OLD.athlete_id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_exercises_insert` AFTER INSERT ON `exercises` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'exercises' AND record_id = NEW.id) AND substr(NEW.id, 1, 3) <> 'ex_' BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('exercises', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_exercises_update` AFTER UPDATE ON `exercises` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'exercises' AND record_id = NEW.id) AND substr(NEW.id, 1, 3) <> 'ex_' BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('exercises', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_exercises_delete` AFTER DELETE ON `exercises` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'exercises' AND record_id = OLD.id) AND substr(OLD.id, 1, 3) <> 'ex_' BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('exercises', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_programs_insert` AFTER INSERT ON `programs` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'programs' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('programs', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_programs_update` AFTER UPDATE ON `programs` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'programs' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('programs', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_programs_delete` AFTER DELETE ON `programs` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'programs' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('programs', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_program_phases_insert` AFTER INSERT ON `program_phases` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'program_phases' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('program_phases', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_program_phases_update` AFTER UPDATE ON `program_phases` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'program_phases' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('program_phases', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_program_phases_delete` AFTER DELETE ON `program_phases` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'program_phases' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('program_phases', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_workout_templates_insert` AFTER INSERT ON `workout_templates` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'workout_templates' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('workout_templates', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_workout_templates_update` AFTER UPDATE ON `workout_templates` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'workout_templates' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('workout_templates', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_workout_templates_delete` AFTER DELETE ON `workout_templates` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'workout_templates' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('workout_templates', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_template_exercise_slots_insert` AFTER INSERT ON `template_exercise_slots` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'template_exercise_slots' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('template_exercise_slots', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_template_exercise_slots_update` AFTER UPDATE ON `template_exercise_slots` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'template_exercise_slots' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('template_exercise_slots', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_template_exercise_slots_delete` AFTER DELETE ON `template_exercise_slots` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'template_exercise_slots' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('template_exercise_slots', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_workout_sessions_insert` AFTER INSERT ON `workout_sessions` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'workout_sessions' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('workout_sessions', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_workout_sessions_update` AFTER UPDATE ON `workout_sessions` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'workout_sessions' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('workout_sessions', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_workout_sessions_delete` AFTER DELETE ON `workout_sessions` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'workout_sessions' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('workout_sessions', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_logged_exercises_insert` AFTER INSERT ON `logged_exercises` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'logged_exercises' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('logged_exercises', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_logged_exercises_update` AFTER UPDATE ON `logged_exercises` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'logged_exercises' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('logged_exercises', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_logged_exercises_delete` AFTER DELETE ON `logged_exercises` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'logged_exercises' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('logged_exercises', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_logged_sets_insert` AFTER INSERT ON `logged_sets` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'logged_sets' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('logged_sets', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_logged_sets_update` AFTER UPDATE ON `logged_sets` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'logged_sets' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('logged_sets', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_logged_sets_delete` AFTER DELETE ON `logged_sets` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'logged_sets' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('logged_sets', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_session_cards_insert` AFTER INSERT ON `session_cards` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'session_cards' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('session_cards', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_session_cards_update` AFTER UPDATE ON `session_cards` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'session_cards' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('session_cards', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_session_cards_delete` AFTER DELETE ON `session_cards` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'session_cards' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('session_cards', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_body_measurements_insert` AFTER INSERT ON `body_measurements` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'body_measurements' AND record_id = NEW.id) AND NEW.source = 'manual' BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('body_measurements', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_body_measurements_update` AFTER UPDATE ON `body_measurements` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'body_measurements' AND record_id = NEW.id) AND NEW.source = 'manual' BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('body_measurements', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_body_measurements_delete` AFTER DELETE ON `body_measurements` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'body_measurements' AND record_id = OLD.id) AND OLD.source = 'manual' BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('body_measurements', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_sleep_entries_insert` AFTER INSERT ON `sleep_entries` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'sleep_entries' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('sleep_entries', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_sleep_entries_update` AFTER UPDATE ON `sleep_entries` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'sleep_entries' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('sleep_entries', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_sleep_entries_delete` AFTER DELETE ON `sleep_entries` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'sleep_entries' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('sleep_entries', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_daily_check_ins_insert` AFTER INSERT ON `daily_check_ins` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'daily_check_ins' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('daily_check_ins', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_daily_check_ins_update` AFTER UPDATE ON `daily_check_ins` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'daily_check_ins' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('daily_check_ins', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_daily_check_ins_delete` AFTER DELETE ON `daily_check_ins` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'daily_check_ins' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('daily_check_ins', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_plans_insert` AFTER INSERT ON `meal_plans` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_plans' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_plans', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_plans_update` AFTER UPDATE ON `meal_plans` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_plans' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_plans', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_plans_delete` AFTER DELETE ON `meal_plans` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_plans' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_plans', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_slots_insert` AFTER INSERT ON `meal_slots` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_slots' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_slots', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_slots_update` AFTER UPDATE ON `meal_slots` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_slots' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_slots', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_slots_delete` AFTER DELETE ON `meal_slots` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_slots' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_slots', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_slot_skips_insert` AFTER INSERT ON `meal_slot_skips` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_slot_skips' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_slot_skips', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_slot_skips_update` AFTER UPDATE ON `meal_slot_skips` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_slot_skips' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_slot_skips', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_slot_skips_delete` AFTER DELETE ON `meal_slot_skips` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_slot_skips' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_slot_skips', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_daily_nutrition_logs_insert` AFTER INSERT ON `daily_nutrition_logs` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'daily_nutrition_logs' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('daily_nutrition_logs', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_daily_nutrition_logs_update` AFTER UPDATE ON `daily_nutrition_logs` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'daily_nutrition_logs' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('daily_nutrition_logs', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_daily_nutrition_logs_delete` AFTER DELETE ON `daily_nutrition_logs` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'daily_nutrition_logs' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('daily_nutrition_logs', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_log_entries_insert` AFTER INSERT ON `meal_log_entries` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_log_entries' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_log_entries', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_log_entries_update` AFTER UPDATE ON `meal_log_entries` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_log_entries' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_log_entries', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_meal_log_entries_delete` AFTER DELETE ON `meal_log_entries` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'meal_log_entries' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('meal_log_entries', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_saved_foods_insert` AFTER INSERT ON `saved_foods` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'saved_foods' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('saved_foods', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_saved_foods_update` AFTER UPDATE ON `saved_foods` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'saved_foods' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('saved_foods', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_saved_foods_delete` AFTER DELETE ON `saved_foods` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'saved_foods' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('saved_foods', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_beverage_containers_insert` AFTER INSERT ON `beverage_containers` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'beverage_containers' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('beverage_containers', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_beverage_containers_update` AFTER UPDATE ON `beverage_containers` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'beverage_containers' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('beverage_containers', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_beverage_containers_delete` AFTER DELETE ON `beverage_containers` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'beverage_containers' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('beverage_containers', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_consumptions_insert` AFTER INSERT ON `consumptions` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'consumptions' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('consumptions', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_consumptions_update` AFTER UPDATE ON `consumptions` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'consumptions' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('consumptions', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_consumptions_delete` AFTER DELETE ON `consumptions` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'consumptions' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('consumptions', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_ai_recommendations_insert` AFTER INSERT ON `ai_recommendations` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'ai_recommendations' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('ai_recommendations', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_ai_recommendations_update` AFTER UPDATE ON `ai_recommendations` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'ai_recommendations' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('ai_recommendations', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_ai_recommendations_delete` AFTER DELETE ON `ai_recommendations` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'ai_recommendations' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('ai_recommendations', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_ai_feedback_insert` AFTER INSERT ON `ai_feedback` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'ai_feedback' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('ai_feedback', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_ai_feedback_update` AFTER UPDATE ON `ai_feedback` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'ai_feedback' AND record_id = NEW.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('ai_feedback', NEW.id, 'upsert', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
--> statement-breakpoint
CREATE TRIGGER `sync_capture_ai_feedback_delete` AFTER DELETE ON `ai_feedback` WHEN (SELECT paused FROM sync_capture_guard WHERE id = 1) = 0 AND NOT EXISTS (SELECT 1 FROM sync_applying WHERE table_name = 'ai_feedback' AND record_id = OLD.id) BEGIN INSERT INTO sync_changes (table_name, record_id, op, changed_at) VALUES ('ai_feedback', OLD.id, 'delete', CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)) ON CONFLICT(table_name, record_id) DO UPDATE SET op = excluded.op, changed_at = excluded.changed_at; END;
