const {
  withAppBuildGradle,
  withProjectBuildGradle,
} = require('expo/config-plugins');

const NATIVE_MODULE_STAGING_MARKER =
  '// @generated by withShortCxxPath: native module C++ staging';

/**
 * Windows only: this project's absolute path is deep enough that the C++ codegen
 * object files for autolinked native modules (react-native-safe-area-context,
 * react-native-screens, react-native-svg) exceed the 260-character MAX_PATH limit
 * under the default module-local `.cxx` staging directories, since CMake mirrors
 * the full absolute source path inside them. Redirecting the app and the two C++
 * animation modules to short paths keeps the mirrored paths under the limit.
 */
module.exports = function withShortCxxPath(config) {
  config = withProjectBuildGradle(config, config => {
    if (config.modResults.language !== 'groovy') return config;
    if (config.modResults.contents.includes(NATIVE_MODULE_STAGING_MARKER)) {
      return config;
    }

    config.modResults.contents += `

${NATIVE_MODULE_STAGING_MARKER}
subprojects { subproject ->
    def shortCxxPaths = [
        "react-native-reanimated": "C:/rncxx/reanimated",
        "react-native-worklets": "C:/rncxx/worklets"
    ]
    def shortCxxPath = shortCxxPaths[subproject.name]
    if (shortCxxPath != null) {
        subproject.plugins.withId("com.android.library") {
            subproject.android.externalNativeBuild.cmake.buildStagingDirectory shortCxxPath
        }
    }
}
`;
    return config;
  });

  return withAppBuildGradle(config, config => {
    if (config.modResults.language !== 'groovy') return config;
    if (config.modResults.contents.includes('buildStagingDirectory')) return config;

    config.modResults.contents = config.modResults.contents.replace(
      /^android \{/m,
      'android {\n    externalNativeBuild {\n        cmake {\n            buildStagingDirectory "C:/rncxx/pulso"\n        }\n    }\n',
    );
    return config;
  });
};
