const { withProjectBuildGradle } = require('expo/config-plugins');

const MARKER = '// @generated by withAdsKotlinMetadata';

/**
 * react-native-google-mobile-ads 16.5.x pins play-services-ads 25.4.0, whose
 * jar ships .kotlin_module metadata at binary version 2.3.0. Expo SDK 56 builds
 * with the Kotlin 2.1.x compiler, which refuses to read it and fails
 * :react-native-google-mobile-ads:compileDebugKotlin outright.
 *
 * Downgrading the ads SDK is not an option: the module's own Kotlin source
 * calls 25.x-only APIs (RequestConfiguration.AgeRestrictedTreatment), so
 * anything below 25.4.0 fails to compile for a different reason.
 *
 * The offending metadata belongs to Google's *internal* modules (protobuf
 * shims, ad-quality telemetry, coroutine helpers) — none of it is API the
 * Invertase wrapper resolves against, so skipping the version check costs us
 * nothing at runtime. Scoped to this one subproject on purpose: every other
 * module must keep the check, or a genuine metadata mismatch would compile
 * cleanly and then blow up on device.
 *
 * Remove once Expo ships a Kotlin 2.3+ toolchain.
 */
module.exports = function withAdsKotlinMetadata(config) {
  return withProjectBuildGradle(config, config => {
    if (config.modResults.language !== 'groovy') return config;
    if (config.modResults.contents.includes(MARKER)) return config;

    config.modResults.contents += `

${MARKER}
subprojects { subproject ->
    if (subproject.name == "react-native-google-mobile-ads") {
        subproject.tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
            compilerOptions {
                freeCompilerArgs.add("-Xskip-metadata-version-check")
            }
        }
    }
}
`;
    return config;
  });
};
