export const ACTION_LABEL: Record<string, string> = {
  "user.suspended": "Cuenta suspendida",
  "user.reactivated": "Cuenta reactivada",
  "user.role_changed": "Rol cambiado",
  "user.plus_granted": "PULSO Plus activado",
  "user.plus_revoked": "PULSO Plus quitado",
  "professional.approved": "Profesional aprobado",
  "professional.rejected": "Profesional rechazado",
  "report.resolved": "Reporte resuelto",
  "report.dismissed": "Reporte descartado",
  "exercise.create": "Ejercicio creado",
  "exercise.update": "Ejercicio editado",
  "exercise.hide": "Ejercicio ocultado",
  "exercise.show": "Ejercicio visible de nuevo",
  "exercise.revert": "Ejercicio restaurado al original",
  "food.create": "Alimento creado",
  "food.update": "Alimento editado",
  "food.delete": "Alimento eliminado",
  "media.upload": "Animación subida",
};
